require("core.options")
require("core.keymaps")
require("plugins/lazynvim-init")

--require("plugins/plugins-setup")
require("plugins/lualine")
require("plugins.nvim-tree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.comment")
require("plugins.autopair")
require("plugins.telescope")
--require("plugins.cmp")
